### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/infografia-MaGuadalupeQuiroz-1#2]
![INFOGRAFIA GPS](https://user-images.githubusercontent.com/72761157/132573337-5d030891-8093-4e71-831c-32ecd99906a2.jpg)

**Comment by Jaci14** [comment]
Presenta ideas claras y concisas, la información esta bien detallada y sintetizada por lo que es entendible desde que comienzas a leer.
Utiliza un diseño muy agradable. Utiliza colores, ilustraciones y tipografía muy atractivas para el receptor, el tamaño de la letra es adecuada y los elementos visuales relacionan el tema con la información en todo momento.  
No contiene ninguna falta ortográfica y utiliza mas de 8 ideas centrales.  

calificación: 20%

**Comment by Jaci14** [comment]
La información es breve y precisa, e resume adecuadamente el video de la "web binar", relaciona las ideas entre sí en un solo texto y la síntesis cumple con los criterios de diseños planteados. 

calificación: 19 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
